### ISSUE TITLE
Unable to verify the first certificate error over HTTPS

### ISSUE THREAD

**Issue by michok34** [kafkajs/confluent-schema-registry#125]
when using:
```
...
const schemaRegistry = new SchemaRegistry({host: 'https://serveraddress:8443'});
await schemaRegistry.encode(registryId, jsonPayload);
...
```
Answer is:
ResponseError: Confluent_Schema_Registry - Error, status 400
Stacktrace:
```
Error: Error: unable to verify the first certificate
        at Object.dispatchError (.../node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
        at Request.<anonymous> (.../node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
        at Request.emit (events.js:215:7)
        at Request.onRequestError (.../node_modules/request/request.js:881:8)
        at ClientRequest.emit (events.js:210:5)
        at TLSSocket.socketErrorListener (_http_client.js:406:9)
        at TLSSocket.emit (events.js:210:5)
        at emitErrorNT (internal/streams/destroy.js:92:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
        at processTicksAndRejections (internal/process/task_queues.js:80:21) undefined
```

Server has self signed certificate and I'm not able to set security context (ca, cert, key...) to SchemaRegistry

Did I miss configuration options?

**Comment by Nevon** [comment]
You can pass an `Agent` instance to the constructor, which in turn can receive the secure context options, including `ca`, `cert` and `key`: https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options

For example:

```ts
import { readFileSync } from 'fs'
import { Agent } from 'https'

const registry = new SchemaRegistry({
  host: 'https://registry:8081/',
  agent: new Agent({
    key: readFileSync('/path/to/my-key.pem'),
    cert: readFileSync('/path/to/my-cert.pem')
  })
})
```

While the specific case of using self-signed certificates is not explicitly mentioned, the possibility of providing a custom agent is documented here: https://kafkajs.github.io/confluent-schema-registry/docs/usage#http-agent

**Comment by michok34** [comment]
@Nevon Thanks. However it probably worth a documentation update to cover that case.
