### ISSUE TITLE
Unable to register schemas with canonical forms that reduce to a primitive type

### ISSUE THREAD

**Issue by BryceCicada** [kafkajs/confluent-schema-registry#157]
I'd like to use a schema-registry avro schema to encode a kafka message key.  Most of the time, the key is pretty simple like a string or a long.  Other times, it's more complex and I can use a record type.  

When the key isn't a record, but it's just a primitive type, I'm struggling to register the schema.  For example:
```
      const schemaRegistry = new SchemaRegistry({host: "http://my-registry:8081"})
      await schemaRegistry.register({type: SchemaType.AVRO, schema: '"string"'})
```
gives:
```
     ConfluentSchemaRegistryArgumentError: Invalid name: undefined
      at AvroHelper.validate (node_modules/@kafkajs/confluent-schema-registry/src/AvroHelper.ts:26:13)
      at SchemaRegistry.register (node_modules/@kafkajs/confluent-schema-registry/src/SchemaRegistry.ts:106:12)
      at Context.<anonymous> (test/service-bus/serde_test.ts:45:28)
      at processImmediate (internal/timers.js:461:21)
```

I've also tried:
```
      await schemaRegistry.register({type: SchemaType.AVRO, schema: JSON.stringify({type: "string"})})
      await schemaRegistry.register({type: SchemaType.AVRO, schema: JSON.stringify({name: "foo", type: "string"})})
```
which have schemas that reduce to the same avro canonical form as the first example, but these give the same error.

I can register the schemas with the registry directly, eg:
```
$ curl -X POST localhost:8081/subjects/my-topic-key/versions -H "Content-Type: application/json" -d '{"schema": "\"string\""}'
{"id":1}
$ curl -X POST localhost:8081/subjects/my-topic-key/versions -H "Content-Type: application/json" -d '{"schema": "{\"type\": \"string\"}"}'  # NB Same canonical form -> same id from registry
{"id":1} 
$ curl -X POST localhost:8081/subjects/my-topic-key/versions -H "Content-Type: application/json" -d '{"schema": "{\"name\": \"foo\", \"type\": \"string\"}"}' # NB Same canonical form again
{"id":1} 
$ curl localhost:8081/schemas/ids/1
{"schema":"\"string\""}
```
which makes me think that `AvroHelper.validate()` might be a bit too strict in requiring a `name` field on the schema.

**Comment by filipstiglic** [comment]
Hello, any update on this?

**Comment by rogen-code** [comment]
Hit this today and would love to know if anyone has a workaround.
