### ISSUE TITLE
AVSC files without a top level name, type and fields are considered invalid, but it shouldn't.

### ISSUE THREAD

**Issue by samhwang** [kafkajs/confluent-schema-registry#169]
Hey KafkaJS Team, just wanted to started that this project is superb. However, I just came into this weird hiccup, which I think shouldn't be. I'm still new to how Kafka and Avro (and KafkaJS) works, so if I'm wrong, please lead me in the right direction :D.

# Issue Description

I'm trying to read an avro file that does not have a top level record, but instead it has an array of records.

```avsc
[
  {
    "name": "ARecord",
    "namespace": "com.samhwang.testavro",
    "type": "record",
    "fields": [
      {"name": "first_name", "type": "string"},
      {"name": "last_name", "type": "string"}
    ]
  },
  {
    "name": "BRecord",
    "namespace": "com.samhwang.testavro",
    "type": "record",
    "fields": [
      {"name": "test_attr", "type": "string"}
    ]
  }
]
```

This is validated to be correct, both by a locally hosted Kafka Schema Registry (using the docker image [`confluentinc/cp-schema-registry:6.2.1`](https://hub.docker.com/r/confluentinc/cp-schema-registry)) and on Confluent Cloud (see screenshot attached).
![Screen Shot 2021-11-12 at 2 18 05 pm](https://user-images.githubusercontent.com/4188758/141403401-f99da710-0234-409c-b606-d060a6602675.png)

# Reproduction steps/repo

I have created a sample repo in Typescript to reproduce this issue at: [samhwang/test-node-kafka](https://github.com/samhwang/test-node-kafka).

# Reproduction steps

- Install the reproduction repo
```shell
git clone https://github.com/samhwang/test-node-kafka.git
cd test-node-kafka
npm install
docker-compose up -d
```

- Register schema via a http request to schema registry. This works fine.
```shell
❯ npx ts-node src/register_schema_axios.ts
{
  'Schema Registry URL': 'http://localhost:8081',
  Topic: 'test-topic',
  'Schema file': '/Users/sam/projects/HungryHungry/docker_stuff/test-node-kafka/src/sam.avsc'
}
Schema Registered Successfully! { id: 1 }
```

- Register schema via using the package `@kafkajs/confluent-schema-registry`. This just breaks at just reading the `avsc` file.
```shell
❯ npx ts-node src/register_schema_kafkajs.ts
ConfluentSchemaRegistryInvalidSchemaError: /Users/sam/projects/test-node-kafka/src/sam.avsc is not recognized as a valid AVSC file (expecting valid top-level name, type and fields attributes)
    at validatedSchema (/Users/sam/projects/HungryHungry/docker_stuff/test-node-kafka/node_modules/@kafkajs/confluent-schema-registry/src/utils/readAVSC.ts:21:11)
    at readAVSCAsync (/Users/sam/projects/HungryHungry/docker_stuff/test-node-kafka/node_modules/@kafkajs/confluent-schema-registry/src/utils/readAVSC.ts:35:10)
    at async registerSchema (/Users/sam/projects/HungryHungry/docker_stuff/test-node-kafka/src/register_schema_kafkajs.ts:8:24)
```

**Comment by pmsfc** [comment]
@Nevon We're having the same issue when consuming a topic with that schema without top level record.

For example this code:
```
// this fails!
registry.decode(buffer, {
      [SchemaType.AVRO]: {readerSchema}, // We can't use a RawAvroSchema type without a Record
    })
```

But if we use the schema id that included in the Kafka message it works.
```
// this works!
registry.decode(buffer)
```
