### ISSUE TITLE
Issue with registering a schema of type array with multiple items inside

### ISSUE THREAD

**Issue by R1k3r** [kafkajs/confluent-schema-registry#214]
Hello altogether,

I am using the module "@kafkajs/confluent-schema-registry" in version "3.2.1".

I have observed an issue with the schema registry.
Let us assume, I have an object ("PersonList") inside my code that consists of multiple other objects ("Person").
The JSON representation of this object looks as follows:

`[{
    "id": "123456789",
    "name": "peter",
    "surname": "lewis"
},
{
    "id": "234567890",
    "name": "jane",
    "surname": "foster"
}]`

The corresponding AVRO schema should in turn look as follows:

`{
  "name": "PersonList",
  "type": "array",
  "namespace": "com.myexample", 
  "items": {
    "name": "Person",
    "type": "record",
    "fields": [
      {
        "name": "id",
        "type": "string"
      },
      {
        "name": "name",
        "type": "string"
      },
      {
        "name": "surname",
        "type": "string"
      }
    ]
  }
}`

But above gives me an error, when I try to register the schema.
The error output is:

` ConfluentSchemaRegistryArgumentError: Invalid name: undefined
    at AvroHelper.validate (...\node_modules\@kafkajs\confluent-schema-registry\src\AvroHelper.ts:40:11)
    at SchemaRegistry.register (...\node_modules\@kafkajs\confluent-schema-registry\src\SchemaRegistry.ts:117:9)`

I tried to get into the code of the AvroHelper.js file and logged the "avroSchema" of the "getAvroSchema(schema, opts)" function.
The output is:

`<ref *2> ArrayType {
  _hash: Hash { str: undefined },
  name: undefined,
  aliases: undefined,
  doc: undefined,
  itemsType: <ref *1> RecordType {
    _hash: Hash { str: undefined },
    name: 'Person',
    aliases: [],
    doc: undefined,
    _fieldsByName: { id: [Field], name: [Field], surname: [Field] },
    fields: [ [Field], [Field], [Field] ],
    _branchConstructor: [Function: Branch$] { type: [Circular *1] },
    _isError: false,
    recordConstructor: [Function: Person] {
      getType: [Function (anonymous)],
      type: [Circular *1]
    },
    _read: [Function: readPerson],
    _skip: [Function: skipPerson],
    _write: [Function: writePerson],
    _check: [Function: checkPerson]
  },
  _branchConstructor: [Function: Branch$] { type: [Circular *2] }
}`

As you can see above, the "name" is omitted for some reason. Hence, I actually get the "Invalid name: undefined" error when trying to register my schema, although I have defined a "name" as well as a "namespace" in my schema.

Am I getting something wrong here?

**Comment by R1k3r** [comment]
I think https://github.com/confluentinc/schema-registry/issues/1298 is more or less pointing to my issue as well... I will try to workaround with that hint.

**Comment by R1k3r** [comment]
Had to do it some other way.
What my code returned was the following (an array of objects):

`[{ "id": "123456789", "name": "peter", "surname": "lewis" }, { "id": "234567890", "name": "jane", "surname": "foster" }]`

I actually changed this to return the following (a list object with an array of objects inside):

`{list: [{ "id": "123456789", "name": "peter", "surname": "lewis" }, { "id": "234567890", "name": "jane", "surname": "foster" }]}`

In this case, the avro schema definition looks as follows:

```
{
	"name": "PersonList",
	"namespace": "com.myexample",
	"type":"record",
	"fields":[
		{
			"name":"list",
			"type":{
				"type": "array",  
				"items":{
					"name":"Person",
					"type":"record",
					"fields":[
						{ "name": "id", "type": "string" },
						{ "name": "name", "type": "string" },
						{ "name": "surname", "type": "string" }
					]
				}
			}
		}
	] 
}
```

Closing the issue as I got it resolved as above.
