### ISSUE TITLE
Error deserialising message

### ISSUE THREAD

**Issue by brunodomenici** [kafkajs/confluent-schema-registry#33]
Hi,

I trying to consume messages produced by Java (I guess) and I'm receiving this error:

```
{"level":"ERROR","timestamp":"2019-12-10T16:33:51.828Z","logger":"kafkajs",
"message":"[Runner] Error when calling eachMessage",
"topic":"<omitted>-SELLING-PRICE-V1-CURRENT",
"partition":2,
"offset":"13456244",
"stack":"Error: invalid \"string\": null
    at throwInvalidError (***/examples/nodejs/kafkajs/node_modules/avsc/lib/types.js:3023:9)
    at StringType._check (***/examples/nodejs/kafkajs/node_modules/avsc/lib/types.js:1066:5)
    at StringType.PrimitiveType._copy (***/examples/nodejs/kafkajs/node_modules/avsc/lib/types.js:790:8)
    at UnwrappedUnionType._copy (***/examples/nodejs/kafkajs/node_modules/avsc/lib/types.js:1382:17)
    at new Field (***/examples/nodejs/kafkajs/node_modules/avsc/lib/types.js:2806:20)
    at RecordType.<anonymous> (***/examples/nodejs/kafkajs/node_modules/avsc/lib/types.js:2109:17)
    at Array.map (<anonymous>)
    at new RecordType (***/examples/nodejs/kafkajs/node_modules/avsc/lib/types.js:2108:45)
    at ***/examples/nodejs/kafkajs/node_modules/avsc/lib/types.js:226:14
    at Function.Type.forSchema (***/examples/nodejs/kafkajs/node_modules/avsc/lib/types.js:227:7)"}
```

The AVRO Schema seems pretty straightforward, but I'm not sure which AVRO's specification was used by producer application:

```
{
    "type": "record",
    "name": "**ommited***",
    "namespace": "**ommited***",
    "fields": [{
        "name": "storeId",
        "type": "int"
    }, {
        "name": "productId",
        "type": "int"
    }, {
        "name": "extId",
        "type": "int"
    }, {
        "name": "price",
        "type": "string"
    }, {
        "name": "currency",
        "type": "string"
    }, {
        "name": "type",
        "type": {
            "type": "enum",
            "name": "PriceType",
            "symbols": ["NORMAL", "DISCOUNT", "CROSSED"]
        }
    }, {
        "name": "priceStartDate",
        "type": "string"
    }, {
        "name": "ecaCode",
        "type": ["string", "null"],
        "default": null
    }, {
        "name": "operationId",
        "type": ["int", "null"],
        "default": null
    }, {
        "name": "priceWithoutVat",
        "type": ["string", "null"],
        "default": null
    }, {
        "name": "normalPrice",
        "type": ["string", "null"],
        "default": null
    }, {
        "name": "normalPriceWithoutVat",
        "type": ["string", "null"],
        "default": null
    }, {
        "name": "crossedPrice",
        "type": ["string", "null"],
        "default": null
    }, {
        "name": "vatCode",
        "type": ["string", "null"],
        "default": null
    }, {
        "name": "vatRate",
        "type": ["string", "null"],
        "default": null
    }, {
        "name": "unitSale",
        "type": ["string", "null"],
        "default": null
    }, {
        "name": "unitCapacity",
        "type": ["string", "null"],
        "default": null
    }, {
        "name": "capacityQuantity",
        "type": ["string", "null"],
        "default": null
    }, {
        "name": "pricePerUnitCapacity",
        "type": ["string", "null"],
        "default": null
    }, {
        "name": "discountPercentage",
        "type": ["string", "null"],
        "default": null
    }, {
        "name": "discount",
        "type": ["string", "null"],
        "default": null
    }, {
        "name": "displayDiscount",
        "type": [{
            "type": "record",
            "name": "DisplayDiscount",
            "fields": [{
                "name": "type",
                "type": {
                    "type": "enum",
                    "name": "DisplayDiscountType",
                    "symbols": ["PERCENTAGE", "VALUE"]
                }
            }, {
                "name": "value",
                "type": "string"
            }]
        }, "null"],
        "default": null
    }, {
        "name": "originalStoreId",
        "type": ["int", "null"],
        "default": null
    }, {
        "name": "priceEndDate",
        "type": ["string", "null"],
        "default": null
    }, {
        "name": "updateDate",
        "type": ["string", "null"],
        "default": null
    }, {
        "name": "priceAttributes",
        "type": [{
            "type": "record",
            "name": "PriceAttributes",
            "fields": [{
                "name": "activeEcoTaxes",
                "type": {
                    "type": "array",
                    "items": "string"
                }
            }, {
                "name": "deeeAmounts",
                "type": {
                    "type": "array",
                    "items": {
                        "type": "record",
                        "name": "DEEEAmount",
                        "fields": [{
                            "name": "startDate",
                            "type": "string"
                        }, {
                            "name": "endDate",
                            "type": ["string", "null"],
                            "default": null
                        }, {
                            "name": "amount",
                            "type": "string"
                        }, {
                            "name": "currency",
                            "type": "string"
                        }, {
                            "name": "nomencId",
                            "type": "int"
                        }]
                    }
                }
            }]
        }, "null"],
        "default": null
    }]
}
```

Any idea?

Thanks a lot!

**Comment by gioragutt** [comment]
Well, look dude... I'm not quite sure what you expect someone here to say about it.

You show your error (which is pretty straight forward), you paste a big-ass `avsc`, and basically say - solve this shit.

The thing is - you answered your own question - **but I'm not sure which AVRO's specification was used by producer application**.

The only thing you can possibly do in this situation is figure out what's up with the producer application.
Look at the schema of your topic in your schema-registry, and talk to the developer of the producer application you're working with.

That's the only advice I can give.

**Comment by brunodomenici** [comment]
Hello,
Yes, it was a problem with the producer. Sorry about that.
Thanks a lot!
