### ISSUE TITLE
specify which schema?

### ISSUE THREAD

**Issue by Viral** [kafkajs/confluent-schema-registry#36]
how do I specify which schema to pull/read from the registry?

```
const registry = new SchemaRegistry({
  host: 'http://localhost:2181',
  auth: {
    username: '***',
    password: '***',
  },
})

const payload = await registry.decode(buffer)

```

this is my consumer code.... how do I integrate the above in with the below???

```
  await client.consumer.connect();
  await client.consumer.subscribe({ topic: process.env.KAFKA_TOPIC });
  await client.consumer.run({
    eachBatch: async ({ batch, resolveOffset, heartbeat, isRunning, isStale }) => {

      const data = {};
      for (let message of batch.messages) {
        data[message.key.toString()] = message.value.toString();
        resolveOffset(message.offset);
        await heartbeat();
      }
      client.processMessage(data);

    }
  });
```

**Comment by tulios** [comment]
Just for future reference, the schema id is encoded in the payload, so you don't have to do anything special. Use the decode method and the correct schema will be used to parse the payload.

**Comment by Viral** [comment]
```
node src/index.js
ResponseError: Confluent_Schema_Registry - HTTP 404 Not Found
    at C:\Users\user\dev\node\pint-producer\node_modules\@kafkajs\confluent-schema-registry\dist\api\middleware\errorMiddleware.js:16:37
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'ResponseError',
  status: 404,
  unauthorized: false,
  url: 'get https://schema-registry.privatedomain.com/schemas/ids/%5Bobject%20Object%5D'
}
```

any idea what this means?
