### ISSUE TITLE
Error: error registering schemas generated by avdl files with imports

### ISSUE THREAD

**Issue by chualanagit** [kafkajs/confluent-schema-registry#65]
Hi, I have some trouble registering schemas generated by avdl files with any sort of import. I was even running the [test cases](https://github.com/kafkajs/confluent-schema-registry/blob/master/fixtures/avdl/import.avdl) in the confluent_schema_registry repo and that also fails. [This](https://kafkajs.github.io/confluent-schema-registry/docs/usage#uploading-schemas) is how I am creating and registering the schema, by using `avdlToAVSCAsync`. Here is the error msg: 
`ResponseError: Confluent_Schema_Registry - Input schema is an invalid Avro schema
    at /Users/ac01980/code/products-catalog-importer/node_modules/@kafkajs/confluent-schema-registry/src/api/middleware/errorMiddleware.ts:30:47
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 422,
  unauthorized: false,
  url: 'post https://schema-registry-ssl-tst-1.content-hub-kafka.rmneng-test.com/subjects/com.org.domain.fixtures5.Import/versions'
}
Confluent_Schema_Registry - Input schema is an invalid Avro schema`

**Comment by chualanagit** [comment]
Update: seems to be related to an avdl importing another from the same dir. If I placed the imported avdl in a subdirectory, it works. For context, I'm using [import.avdl](https://github.com/kafkajs/confluent-schema-registry/blob/master/fixtures/avdl/import.avdl) and [simple.avdl](https://github.com/kafkajs/confluent-schema-registry/blob/master/fixtures/avdl/simple.avdl) as example. The resulting JSON.stringify string is 
`{"namespace":"com.org.domain.fixtures","type":"record","name":"Import","fields":[{"type":"com.org.domain.fixtures.Simple","name":"simple"}]}`. 
If you copy and paste that to https://json-schema-validator.herokuapp.com/avro.jsp, it will show the error of the schema.

**Comment by hpurmann** [comment]
Hey @chualanagit. We have seen this problem as well when calling the `avdlToAVSCAsync` function multiple times in quick succession, not waiting for the result of the first call. I was [able to reproduce the problem](https://github.com/hpurmann/avro-schema-import-test).

**Comment by Nevon** [comment]
Thanks for the repro case @hpurmann!

Based on your report, I feel reasonably confident that this is actually an issue in [avsc](https://github.com/mtth/avsc). `avdlToAVSCAsync` doesn't do a whole lot more than just delegating to [avsc's `assembleProtocol` function](https://github.com/mtth/avsc/blob/64179935e31947fa535e757df4c075dbbfac05ad/lib/specs.js#L29-L248):

https://github.com/kafkajs/confluent-schema-registry/blob/b342f4eb42599447a39c9506ca501e3a59afc7c3/src/utils/avdlToAVSC.ts#L92-L106

**Comment by hpurmann** [comment]
That's it! I tried as you suggested and it works. Now one of us could write a good unit test and fix it. Good find, @Nevon 

Have you figured out how to run the unit tests on this project? `yarn test:unit` gives me a lot of error in `src/SchemaRegistry.spec.ts`.

```
Test Suites: 2 failed, 1 passed, 3 total
Tests:       30 failed, 1 skipped, 3 passed, 34 total
Snapshots:   0 total
Time:        29.242s
Ran all test suites.
```

**Comment by erikengervall** [comment]
> Have you figured out how to run the unit tests on this project?

The unit tests for this project is in fact integration tests and is run using `yarn test`. Note that it requires Docker running on your machine.
